parameters:
    anyx.authentication.listener.form.class: Anyx\LoginGateBundle\Security\UsernamePasswordFormAuthenticationListener
services:
    anyx.login_failure.storage.session:
        class: Anyx\LoginGateBundle\Storage\SessionStorage
    anyx.login_failure.storage.doctrine:
        class: Anyx\LoginGateBundle\Storage\SessionStorage
    anyx.login_failure.brute_force_checker:
        class: Anyx\LoginGateBundle\Service\BruteForceChecker
        arguments: ['@anyx.login_failure.storage', '%anyx.login_failure.brute_force_checker_options%']
    anyx.login_failure.handler:
        class: Anyx\LoginGateBundle\EventHandler\LoginFailureHandler
        arguments: ['@anyx.login_failure.storage']
    anyx.login_success.handler:
        class: Anyx\LoginGateBundle\EventHandler\LoginSuccessHandler
        arguments: ['@anyx.login_failure.storage']