services:
  - mongodb

language: php
sudo: false

php:
  - 5.6

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*

before_install:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
  - composer update --prefer-dist --no-interaction

script:
  - bin/phpunit -v -c phpunit.mysql.xml
  - bin/phpunit -v -c phpunit.mongodb.xml
